CREATE TABLE IF NOT EXISTS questions(
    question_id INT UNIQUE NOT NULL,
    difficulty INT NOT NULL,
    question_body VARCHAR(500) NOT NULL,
    answer_1 VARCHAR(200) NOT NULL,
    answer_2 VARCHAR(200) NOT NULL,
    answer_3 VARCHAR(200) NOT NULL,
    answer_4 VARCHAR(200) NOT NULL,
    question_answer VARCHAR(200) NOT NULL,
    PRIMARY KEY(question_id)
); CREATE TABLE IF NOT EXISTS students(
    student_id INT AUTO_INCREMENT NOT NULL,
    sid INT,
    first_name VARCHAR(40) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    dob DATE NOT NULL,
    date_quiz_taken DATE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    expected_term VARCHAR(20),
    previous_education VARCHAR(100),
    previous_classes VARCHAR(300),
    question_1 VARCHAR(100),
    question_2 VARCHAR(100),
    question_3 VARCHAR(100),
    question_4 VARCHAR(100),
    question_5 VARCHAR(100),
    question_6 VARCHAR(100),
    question_7 VARCHAR(100),
    question_8 VARCHAR(200),
    question_9 VARCHAR(100),
    question_10 VARCHAR(100),
    question_11 VARCHAR(100),
    question_12 VARCHAR(100),
    question_13 VARCHAR(100),
    question_14 VARCHAR(100),
    question_15 VARCHAR(100),
    question_16 VARCHAR(100),
    question_17 VARCHAR(100),
    question_18 VARCHAR(100),
    question_19 VARCHAR(100),
    question_20 VARCHAR(100),
    question_21 VARCHAR(100),
    question_22 VARCHAR(100),
    question_23 VARCHAR(100),
    question_24 VARCHAR(100),
    question_25 VARCHAR(100),
    question_26 VARCHAR(100),
    question_27 VARCHAR(100),
    question_28 VARCHAR(100),
    question_29 VARCHAR(100),
    question_30 VARCHAR(100),
    question_31 VARCHAR(100),
    question_32 VARCHAR(100),
    question_33 VARCHAR(100),
    question_34 VARCHAR(100),
    question_35 VARCHAR(100),
    score INT,
    recommendation INT,
    PRIMARY KEY(student_id)
); CREATE TABLE IF NOT EXISTS admin(
    admin_id INT AUTO_INCREMENT NOT NULL,
    first_name VARCHAR(40) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    students INT,
    PRIMARY KEY(admin_id)
); CREATE TABLE IF NOT EXISTS contact(
    contact_id INT AUTO_INCREMENT NOT NULL,
    contact_name VARCHAR(80) NOT NULL,
    contact_email VARCHAR(40) NOT NULL,
    contact_message VARCHAR(300) NOT NULL,
    PRIMARY KEY(contact_id)
); INSERT INTO admin(
    first_name,
    last_name,
    email,
    PASSWORD
)
VALUES(
    "admin",
    1,
    "admin@mail.com",
    "admin"
);
INSERT INTO admin(
    first_name,
    last_name,
    email,
    PASSWORD
)
VALUES(
    "admin",
    2,
    "admin2@mail.com",
    "admin"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    1,
    1,
    "What will be the output of the following Java code snippet?<br>int x = 5;<br>int y = 3;<br>System.out.println(x + y * 2);",
    "11",
    "16",
    "13",
    "15",
    "11"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    2,
    1,
    "What does the following Java code snippet do?<br>int i = 0;<br>while (i < 5) {<br>&emsp;System.out.print(I + &quot; &quot;);<br>&emsp;i++;<br>}",
    "Prints numbers from 0 to 4 with space separation",
    "Prints numbers from 1 to 5 with space separation",
    " Prints numbers from 0 to 5 with space separation ",
    "Infinite loop",
    "Prints numbers from 0 to 4 with space separation"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    3,
    1,
    "What is the output of the following Java code snippet?<br>int num = -5;<br>if (num > 0) {<br>&emsp;System.out.println(&quot;Positive&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Negative&quot;);<br>}",
    "Positive",
    "Negative",
    "-5",
    "Error",
    "Negative"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    4,
    1,
    "What does the following Java code snippet do?<br>for (int i = 0; i < 5; i++) {<br>&emsp;System.out.println(i * 2 + &quot; &quot;);<br>}",
    "Prints even numbers from 0 to 8 with space seraration",
    "Prints odd numbers from 1 to 9 with space separation",
    "Prints numbers from 0 to 8 with space separation",
    "Infinite loop",
    "Prints even numbers from 0 to 8 with space seraration"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    5,
    1,
    "What will be the value of <em>result</em> in the following Java code snippet?<br>int x = 5;<br>int y = 2;<br>int result = x % y;",
    "1",
    "2",
    "3",
    "0",
    "1"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    6,
    2,
    "Which of the following Java code snippets correctly computes the sum of two integers a and b?",
    "int sum = a - b;",
    "int sum = a * b;",
    "int sum = a / b;",
    "int sum = a + b;",
    "int sum = a + b;"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    7,
    2,
    "What is the result of the following Java code snippet?<br>int x = 10;<br>int y = 3;<br>int result = x % y;",
    "1",
    "2",
    "3",
    "0",
    "1"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    8,
    2,
    "Which Java code snippet correctly implements a conditional structure to determine if a number num is even?",
    "if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
    "if (num / 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
    "if (num == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
    "if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
    "1"
); -- Assuming the correct answer is answer_1 (indexing from 1)
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    9,
    2,
    "Which Java code snippet correctly implements a loop to print numbers from 1 to 5?",
    "for (int i = 1; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
    "for (int i = 0; i < 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
    "for (int i = 1; i < 6; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
    "for (int i = 0; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
    "1"
); -- Assuming the correct answer is answer_1 (indexing from 1)
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    10,
    2,
    "What does the following Java code snippet do?<br>int i = 0;<br>while (i < 5) {<br>&emsp;System.out.print(i * 2 + &quot; &quot;);<br>&emsp;i++;<br>}",
    "Prints numbers from 0 to 4 with space separation",
    "Prints even numbers from 0 to 8 with space separation",
    "Prints numbers from 0 to 8 with space separation",
    "Infinite loop",
    "Prints even numbers from 0 to 8 with space separation"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    11,
    3,
    "Which keyword is used to define a class in Java?",
    "class",
    "void",
    "public",
    "static",
    "class"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    12,
    3,
    "What is the purpose of a constructor in Java?",
    "To create objects",
    "To initialize variables",
    "To define methods",
    "To perform arithmetic operations",
    "To create objects"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    13,
    3,
    "Which of the following statements is true about Java constructors?",
    "Constructors can have a return type",
    "Constructors can be inherited",
    "Constructors can be overloaded",
    "Constructors can be declared static",
    "Constructors can be overloaded"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    14,
    3,
    "Which of the following correctly defines a method named calculateArea in a Java class?",
    "int calculateArea() { }",
    "void calculateArea() { }",
    "calculateArea() { }",
    "public int calculateArea() { }",
    "public int calculateArea() { }"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    15,
    3,
    "What does the following Java code snippet do?<br>public class Rectangle {<br>&emsp;int length;<br>&emsp;int width;<br><br>&emsp;public Rectangle(int l, int w) {<br>&emsp;&emsp;length = l;<br>&emsp;&emsp;width = w;<br>&emsp;}<br><br>&emsp;public int calculateArea() {<br>&emsp;&emsp;return length * width;<br>&emsp;}<br>}",
    "Defines a class named Rectangle with length and width attributes and a method to calculate the area",
    "Defines a method named Rectangle with parameters length and width",
    "Creates an object of the Rectangle class",
    "Initializes length and width variables",
    "Defines a class named Rectangle with length and width attributes and a method to calculate the area"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    16,
    4,
    "Which of the following correctly declares an array of integers named numbers in Java?",
    "int[] numbers;",
    "numbers[];",
    "int numbers[];",
    "array<int> numbers;",
    "int[] numbers"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    17,
    4,
    "What is the correct syntax to access the third element of an array named arr in Java?",
    "arr[2];",
    "arr[3];",
    "arr(3);",
    "arr.get(3);",
    "arr[2];"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    18,
    4,
    "Whatdoes the following Java code snippet do?<br>int[] numbers = {1, 2, 3, 4, 5};<br>int sum = 0;<br>for (int i = 0; i < numbers.length; i++) {<br>&emsp;sum += numbers[i];<br>}",
    "Finds the average of the numbers in the array",
    "Computes the product of the numbers in the array",
    "Calculates the sum of the numbers in the array",
    "Prints the length of the array",
    "Calculates the sum of the numbers in the array"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    19,
    4,
    "Which of the following statements correctly creates an array of String objects named names in Java?",
    "String[] names = new String();",
    "String names[] = new String();",
    "String[] names = new String[5];",
    "String names[] = new String[5];",
    "String[] names = new String();"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    20,
    4,
    "What is the purpose of the length property of an array in Java?",
    "It stores the number of elements in the array",
    "It stores the capacity of the array",
    "It stores the size of the array",
    "It stores the index of the last element in the array",
    "It stores the size of the array"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    21,
    5,
    "Which of the following best describes inheritance in Java?",
    "Inheritance allows a class to inherit properties and behaviors from another class",
    "Inheritance allows a class to have multiple parent classes",
    "Inheritance allows a class to override all methods of the superclass",
    "Inheritance allows a subclass to access private members of the superclass",
    "Inheritance allows a class to inherit properties and behaviors from another class"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    22,
    5,
    "What is the purpose of encapsulation in Java?",
    "Encapsulation allows a class to inherit properties and behaviors from another class",
    "Encapsulation allows data to be hidden and accessed only through the methods of a class",
    "Encapsulation allows a class to have multiple parent classes",
    "Encapsulation allows a subclass to access private members of the superclass",
    "Encapsulation allows data to be hidden and accessed only through the methods of a class"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    23,
    5,
    "Which of the following statements is true about polymorphism in Java?",
    "Polymorphism allows a class to have multiple parent classes",
    "Polymorphism allows a subclass to access private members of the superclass",
    "Polymorphism allows a method to have multiple implementations based on the object it is called with",
    "Polymorphism allows a class to inherit properties and behaviors from another class",
    "Polymorphism allows a method to have multiple implementations based on the object it is called with"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    24,
    5,
    "What is method overriding in Java?",
    "Method overriding allows a subclass to provide a specific implementation of a method that is already defined in its superclass",
    "Method overriding allows a subclass to hide a method from its superclass",
    "Method overriding allows a subclass to access private members of its superclass",
    "Method overriding allows a subclass to have multiple parent classes",
    "Method overriding allows a subclass to provide a specific implementation of a method that is already defined in its superclass"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    25,
    5,
    "Which keyword is used to indicate that a method can be overridden by a subclass in Java?",
    "override",
    "virtual",
    "extends",
    "inherit",
    "extends"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    26,
    6,
    "What Java library is commonly used for creating graphical user interfaces (GUIs)?",
    "JavaFX",
    "Swing",
    "AWT",
    "JavaGUI",
    "JavaFX"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    27,
    6,
    "What is an event-driven program?",
    "A program that runs continuously without any user interaction",
    "A program that responds to user actions or events",
    "A program that executes only once and terminates",
    "A program that generates random events",
    "A program that responds to user actions or events"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    28,
    6,
    "Which of the following components is commonly used to handle user input in a Java GUI?",
    "JLabel",
    "JButton",
    "JTable",
    "JTextArea",
    "JTextArea"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    29,
    6,
    "What is the purpose of an ActionListener in Java GUI programming?",
    "To define the layout of the GUI components",
    "To handle mouse events such as clicks",
    "To handle keyboard events such as key presses",
    "To define the appearance of the GUI components",
    "To handle mouse events such as clicks"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    30,
    6,
    "Which of the following statements is true about event handling in Java GUI programming?",
    "Each GUI component handles its own events",
    "All events in a Java GUI program are handled by a single event handler",
    "Events in Java GUI programming are handled asynchronously",
    "Event handling in Java GUI programming is not supported",
    "Events in Java GUI programming are handled asynchronously"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    31,
    7,
    "What is the purpose of file handling in Java?",
    "To store data in memory",
    "To retrieve data from databases",
    "To read and write data to external files",
    "To perform arithmetic operations",
    "To read and write data to external files"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    32,
    7,
    "Which Java class is commonly used for reading text from external files?",
    "FileReader",
    "FileWriter",
    "BufferedReader",
    "BufferedWriter",
    "BufferedReader"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    33,
    7,
    "What is the purpose of the File class in Java file handling?",
    "To create a new file",
    "To delete a file",
    "To represent a file or directory path",
    "To open a file for reading",
    "To represent a file or directory path"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    34,
    7,
    "Which Java code snippet correctly opens a file named &quot;data.txt&quot; for reading?",
    "File file = new File(&quot;data.txt&quot;);",
    "FileReader fileReader = new FileReader(&quot;data.txt&quot;);",
    "BufferedReader reader = new BufferedReader(new FileReader(&quot;data.txt&quot;));",
    "FileInputStream fis = new FileInputStream(&quot;data.txt&quot;);",
    "FileInputStream fis = new FileInputStream(&quot;data.txt&quot;);"
);
INSERT INTO questions(
    question_id,
    difficulty,
    question_body,
    answer_1,
    answer_2,
    answer_3,
    answer_4,
    question_answer
)
VALUES(
    35,
    7,
    "What is the purpose of the write method in the BufferedWriter class in Java?",
    "To read data from a file",
    "To write data to a file",
    "To delete a file",
    "To close a file",
    "To write data to a file"
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	previous_education,
	previous_classes,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	1,
	NULL,
	"Aspen",
	"Fred",
	"2006-05-17",
	"2024-05-10",
	"af@mail.com",
	"Fall2024",
	"UW",
	"CS100, CS110",
	"11",
	"Prints numbers from 0 to 5 with space separation",
	"-5",
	"Prints numbers from 0 to 8 with space separation",
	"2",
	"int sum = a + b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 1; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints even numbers from 0 to 8 with space separation",
	"public",
	"To create objects",
	"Constructors can be overloaded",
	"public int calculateArea() { }",
	"Defines a method named Rectangle with parameters length and width",
	9,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	2,
	12514575,
	"Frank",
	"Tank",
	"2006-01-04",
	"2024-03-24",
	"ft@mail.com",
	"Winter2024",
	"16",
	"Infinite loop",
	"Negative",
	"Prints even numbers from 0 to 8 with space seraration",
	"1",
	"int sum = a - b;",
	"2",
	"if (num / 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 0; i < 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Infinite loop",
	"void",
	"To initialize variables",
	"Constructors can be inherited",
	"CalculateArea() { }",
	"Defines a method named Rectangle with parameters length and width",
	3,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	previous_education,
	previous_classes,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	3,
	NULL,
	"Bob",
	"Bird",
	"2006-04-12",
	"2023-12-19",
	"bb@mail.com",
	"Fall2024",
	"Green River College",
	"CS100",
	"16", "Prints numbers from 0 to 4 with space separation",
	"Negative",
	"Prints numbers from 0 to 8 with space separation",
	"1",
	"int sum = a + b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 0; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints even numbers from 0 to 8 with space separation",
	"public",
	"To initialize variables",
	"Constructors can be declared static",
	"int calculateArea() { }",
	"Defines a method named Rectangle with parameters length and width",
	8,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	previous_education,
	previous_classes,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	4,
	NULL,
	"Ashley",
	"Green",
	"2005-06-21",
	"2024-05-03",
	"ag@mail.com",
	"Fall2024",
	"WSU",
	"CS100, CS111",
	"11",
	"Prints numbers from 0 to 5 with space separation",
	"Error",
	"Defines a method named Rectangle with parameters length and width",
	"0",
	"int sum = a * b;",
	"2",
	"if (num / 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 0; i < 6; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Infinite loop",
	"void",
	"To perform arithmetic operations",
	"Constructors can be inherited",
	"calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	2,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	5,
	54878122,
	"Bear",
	"Glassman",
	"2006-01-21",
	"2022-08-28",
	"bear@mail.com",
	"Fall2023",
	"13",
	"Prints numbers from 0 to 4 with space separation",
	"-5",
	"Prints odd numbers from 1 to 9 with space separation",
	"3",
	"int sum = a / b;",
	"2",
	"if (num / 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 0; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints numbers from 0 to 8 with space separation",
	"void",
	"To initialize variables",
	"Constructors can have a return type",
	"int calculateArea() { }",
	"Initializes length and width variables",
	1,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	6,
	14478799,
	"Jon",
	"Greg",
	"2006-05-04",
	"2024-03-11",
	"jg@mail.com",
	"Fall2024",
	"11",
	"Prints numbers from 1 to 5 with space separation",
	"Error",
	"Prints numbers from 0 to 8 with space separation",
	"0",
	"int sum = a / b;",
	"2",
	"if (num == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 0; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints numbers from 0 to 4 with space separation",
	"void",
	"To initialize variables",
	"Constructors can be overloaded",
	"public int calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	4,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	previous_education,
	previous_classes,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	7,
	NULL,
	"Ava",
	"Wilson",
	"2004-11-04",
	"2022-12-05",
	"av@mail.com",
	"Fall2023",
	"N/A",
	"No courses",
	"11",
	"Prints numbers from 0 to 4 with space separation",
	"Negative",
	"Infinite loop",
	"2",
	"int sum = a + b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 0; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Infinite loop",
	"class",
	"To perform arithmetic operations",
	"Constructors can be overloaded",
	"calculateArea() { }",
	"Creates an object of the Rectangle class",
	9,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	question_16,
	question_17,
	question_18,
	question_19,
	question_20,
	question_21,
	question_22,
	question_23,
	question_24,
	question_25,
	question_26,
	question_27,
	question_28,
	question_29,
	question_30,
	question_31,
	question_32,
	question_33,
	question_34,
	question_35,
	score,
	recommendation)
VALUES (
	8,
	14888752,
	"Olivia",
	"Walker",
	"2006-05-04",
	"2024-01-20",
	"oli.walker@mail.com",
	"Fall2024",
	"11",
	"Prints numbers from 0 to 4 with space separation",
	"Negative",
	"Prints numbers from 0 to 4 with space separation",
	"1",
	"int sum = a + b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 0; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints even numbers from 0 to 8 with space separation",
	"public",
	"To create objects",
	"Constructors can be overloaded",
	"public int calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	"int[] numbers;",
	"arr[2];",
	"Calculates the sum of the numbers in the array",
	"String[] names = new String();",
	"It stores the number of elements in the array",
	"Inheritance allows a class to inherit properties and behaviors from another class",
	"Encapsulation allows data to be hidden and accessed only through the methods of a class",
	"Polymorphism allows a class to inherit properties and behaviors from another class",
	"Method overriding allows a subclass to access private members of its superclass",
	"extends",
	"JavaFX",
	"A program that responds to user actions or events",
	"JTextArea",
	"To define the layout of the GUI components",
	"All events in a Java GUI program are handled by a single event handler",
	"To read and write data to external files",
	"BufferedReader",
	"To represent a file or directory path",
	"BufferedReader reader = new BufferedReader(new FileReader(&quotdata.txt&quot));",
	"To write data to a file",
	26,
	1
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	previous_education,
	previous_classes,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	question_16,
	question_17,
	question_18,
	question_19,
	question_20,
	question_21,
	question_22,
	question_23,
	question_24,
	question_25,
	question_26,
	question_27,
	question_28,
	question_29,
	question_30,
	question_31,
	question_32,
	question_33,
	question_34,
	question_35,
	score,
	recommendation)
VALUES (
	9,
	NULL,
	"Emily",
	"Chen",
	"2003-07-16",
	"2024-02-01",
	"ec@mail.com",
	"Fall2025",
	"UW",
	"CS100, CS110, CS111",
	"11",
	"Prints numbers from 0 to 4 with space separation",
	"Negative",
	"Prints even numbers from 0 to 8 with space seraration",
	"1",
	"int sum = a + b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 1; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints even numbers from 0 to 8 with space separation",
	"public",
	"To create objects",
	"Constructors can be overloaded",
	"public int calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	"int[] numbers;",
	"arr[2];",
	"Calculates the sum of the numbers in the array",
	"String[] names = new String();",
	"It stores the number of elements in the array",
	"Inheritance allows a class to inherit properties and behaviors from another class",
	"Encapsulation allows data to be hidden and accessed only through the methods of a class",
	"Polymorphism allows a class to have multiple parent classes",
	"Method overriding allows a subclass to provide a specific implementation of a method that is already",
	"extends",
	"JavaFX",
	"A program that runs continuously without any user interaction",
	"JTextArea",
	"To handle keyboard events such as key presses",
	"Events in Java GUI programming are handled asynchronously",
	"To read and write data to external files",
	"BufferedReader",
	"To represent a file or directory path",
	"BufferedReader reader = new BufferedReader(new FileReader(&quotdata.txt&quot));",
	"To read data from a file",
	27,
	1
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	previous_education,
	previous_classes,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	question_16,
	question_17,
	question_18,
	question_19,
	question_20,
	question_21,
	question_22,
	question_23,
	question_24,
	question_25,
	question_26,
	question_27,
	question_28,
	question_29,
	question_30,
	question_31,
	question_32,
	question_33,
	question_34,
	question_35,
	score,
	recommendation)
VALUES (
	10,
	NULL,
	"Theo",
	"Johnson",
	"2004-02-11",
	"2023-11-11",
	"theo.jon@mail.com",
	"Fall2024",
	"Highline College",
	"CS100, CS101",
	"11",
	"Prints numbers from 0 to 4 with space separation",
	"Negative",
	"Prints even numbers from 0 to 8 with space seraration",
	"1",
	"int sum = a + b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 1; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints even numbers from 0 to 8 with space separation",
	"public",
	"To create objects",
	"Constructors can be overloaded",
	"public int calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	"int[] numbers;",
	"arr[2];",
	"Calculates the sum of the numbers in the array",
	"String[] names = new String();",
	"It stores the index of the last element in the array",
	"Inheritance allows a class to have multiple parent classes",
	"Encapsulation allows a class to inherit properties and behaviors from another class",
	"Polymorphism allows a subclass to access private members of the superclass",
	"Method overriding allows a subclass to hide a method from its superclass",
	"extends",
	"JavaFX",
	"A program that runs continuously without any user interaction",
	"JTable",
	"To define the layout of the GUI components",
	"All events in a Java GUI program are handled by a single event handler",
	"To read and write data to external files",
	"BufferedReader",
	"To open a file for reading",
	"FileInputStream fis = new FileInputStream(&quotdata.txt&quot);",
	"To write data to a file",
	21,
	111
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	question_16,
	question_17,
	question_18,
	question_19,
	question_20,
	question_21,
	question_22,
	question_23,
	question_24,
	question_25,
	question_26,
	question_27,
	question_28,
	question_29,
	question_30,
	question_31,
	question_32,
	question_33,
	question_34,
	question_35,
	score,
	recommendation)
VALUES (
	11,
	15748257,
	"Marcus",
	"Nguyen",
	"2002-06-05",
	"2022-04-20",
	"mn@mail.com",
	"Spring2023",
	"11",
	"Prints numbers from 1 to 5 with space separation",
	"Negative",
	"Prints even numbers from 0 to 8 with space seraration",
	"1",
	"int sum = a + b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 1; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints even numbers from 0 to 8 with space separation",
	"public",
	"To create objects",
	"Constructors can be overloaded",
	"public int calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	"int[] numbers;",
	"arr[2];",
	"Calculates the sum of the numbers in the array",
	"String[] names = new String();",
	"It stores the number of elements in the array",
	"Inheritance allows a class to override all methods of the superclass",
	"Encapsulation allows data to be hidden and accessed only through the methods of a class",
	"Polymorphism allows a method to have multiple implementations based on the object it is called with",
	"Method overriding allows a subclass to hide a method from its superclass",
	"virtual",
	"Swing",
	"A program that runs continuously without any user interaction",
	"JButton",
	"To handle keyboard events such as key presses",
	"Event handling in Java GUI programming is not supported",
	"To retrieve data from databases",
	"BufferedReader",
	"To represent a file or directory path",
	"BufferedReader reader = new BufferedReader(new FileReader(&quotdata.txt&quot));",
	"To delete a file",
	20,
	111
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	previous_education,
	previous_classes,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	12,
	NULL,
	"Elijah",
	"Ramirez",
	"2004-10-12",
	"2024-03-10",
	"eram@mail.com",
	"Fall2024",
	"UW Tacoma",
	"CS100, CS110",
	"13",
	"Prints numbers from 0 to 5 with space separation",
	"-5",
	"Prints numbers from 0 to 8 with space separation",
	"0",
	"int sum = a / b;",
	"3",
	"if (num == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 1; i < 6; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints numbers from 0 to 8 with space separation",
	"static",
	"To define methods",
	"Constructors can be overloaded",
	"void calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	2,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	question_16,
	question_17,
	question_18,
	question_19,
	question_20,
	question_21,
	question_22,
	question_23,
	question_24,
	question_25,
	question_26,
	question_27,
	question_28,
	question_29,
	question_30,
	question_31,
	question_32,
	question_33,
	question_34,
	question_35,
	score,
	recommendation)
VALUES (
	13,
	26589548,
	"Sophie",
	"Reynolds",
	"2001-02-28",
	"2022-07-07",
	"rey@mail.com",
	"Fall2023",
	"11",
	"Prints numbers from 0 to 4 with space separation",
	"Negative",
	"Prints even numbers from 0 to 8 with space seraration",
	"1",
	"int sum = a + b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 1; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints even numbers from 0 to 8 with space separation",
	"public",
	"To create objects",
	"Constructors can be overloaded",
	"public int calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	"int[] numbers;",
	"arr[2];",
	"Finds the average of the numbers in the array",
	"String[] names = new String();",
	"It stores the number of elements in the array",
	"Inheritance allows a class to inherit properties and behaviors from another class",
	"Encapsulation allows data to be hidden and accessed only through the methods of a class",
	"Polymorphism allows a class to have multiple parent classes",
	"Method overriding allows a subclass to provide a specific implementation of a method that is already",
	"extends",
	"JavaFX",
	"A program that responds to user actions or events",
	"JTextArea",
	"To handle keyboard events such as key presses",
	"Events in Java GUI programming are handled asynchronously",
	"To read and write data to external files",
	"BufferedReader",
	"To create a new file",
	"BufferedReader reader = new BufferedReader(new FileReader(&quotdata.txt&quot));",
	"To read data from a file",
	26,
	1
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	previous_education,
	previous_classes,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	14,
	NULL,
	"Lucas",
	"Hernandez",
	"2000-10-17",
	"2022-04-05",
	"luc@mail.com",
	"Fall2024",
	"None",
	"None",
	"15",
	"Prints numbers from 0 to 4 with space separation",
	"Error",
	"Infinite loop",
	"2",
	"int sum = a * b;",
	"0",
	"if (num == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 1; i < 6; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Infinite loop",
	"void",
	"To define methods",
	"Constructors can be overloaded",
	"public int calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	4,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	previous_education,
	previous_classes,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	15,
	NULL,
	"Zachary",
	"Carter",
	"2003-01-28",
	"2023-12-28",
	"zc@mail.com",
	"Fall2022",
	"N/A",
	"None",
	"11",
	"Prints numbers from 1 to 5 with space separation",
	"Positive",
	"Infinite loop",
	"3",
	"int sum = a * b;",
	"0",
	"if (num / 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 0; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Infinite loop",
	"void",
	"To initialize variables",
	"Constructors can be overloaded",
	"public int calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	4,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	question_16,
	question_17,
	question_18,
	question_19,
	question_20,
	question_21,
	question_22,
	question_23,
	question_24,
	question_25,
	question_26,
	question_27,
	question_28,
	question_29,
	question_30,
	question_31,
	question_32,
	question_33,
	question_34,
	question_35,
	score,
	recommendation)
VALUES (
	16,
	15847522,
	"Alexander",
	"Lee",
	"2001-07-18",
	"2024-02-01",
	"alee@mail.com",
	"Fall2025",
	"11",
	"Prints numbers from 1 to 5 with space separation",
	"Negative",
	"Prints odd numbers from 1 to 9 with space separation",
	"1",
	"int sum = a + b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 1; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints even numbers from 0 to 8 with space separation",
	"static",
	"To create objects",
	"Constructors can be overloaded",
	"public int calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	"int[] numbers;",
	"arr[2];",
	"Calculates the sum of the numbers in the array",
	"String[] names = new String();",
	"It stores the index of the last element in the array",
	"Inheritance allows a class to override all methods of the superclass",
	"Encapsulation allows a class to have multiple parent classes",
	"Polymorphism allows a class to inherit properties and behaviors from another class",
	"Method overriding allows a subclass to provide a specific implementation of a method that is already",
	"inherit",
	"AWT",
	"A program that executes only once and terminates",
	"JTable",
	"To handle keyboard events such as key presses",
	"Events in Java GUI programming are handled asynchronously",
	"To read and write data to external files",
	"BufferedReader",
	"To open a file for reading",
	"File file = new File(&quotdata.txt&quot);",
	"To close a file",
	19,
	111
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	previous_education,
	previous_classes,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	question_16,
	question_17,
	question_18,
	question_19,
	question_20,
	question_21,
	question_22,
	question_23,
	question_24,
	question_25,
	question_26,
	question_27,
	question_28,
	question_29,
	question_30,
	question_31,
	question_32,
	question_33,
	question_34,
	question_35,
	score,
	recommendation)
VALUES (
	17,
	NULL,
	"Noah",
	"Mitchell",
	"2024-06-15",
	"2023-01-09",
	"mitch.n@mail.com",
	"Fall2024",
	"Highline",
	"CS100, CS110",
	"11",
	"Prints numbers from 0 to 4 with space separation",
	"Negative",
	"Prints even numbers from 0 to 8 with space seraration",
	"1",
	"int sum = a + b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 1; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints even numbers from 0 to 8 with space separation",
	"public",
	"To perform arithmetic operations",
	"Constructors can have a return type",
	"public int calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	"int[] numbers;",
	"arr[2];",
	"Finds the average of the numbers in the array",
	"String[] names = new String();",
	"It stores the number of elements in the array",
	"Inheritance allows a class to inherit properties and behaviors from another class",
	"Encapsulation allows data to be hidden and accessed only through the methods of a class",
	"Polymorphism allows a subclass to access private members of the superclass",
	"Method overriding allows a subclass to provide a specific implementation of a method that is already",
	"override",
	"JavaFX",
	"A program that responds to user actions or events",
	"JTextArea",
	"To define the layout of the GUI components",
	"Event handling in Java GUI programming is not supported",
	"To store data in memory",
	"FileReader",
	"To delete a file",
	"BufferedReader reader = new BufferedReader(new FileReader(&quotdata.txt&quot));",
	"To delete a file",
	20, 
	111
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	18,
	15847584,
	"Mia",
	"Stewart",
	"2005-02-15",
	"2024-01-04",
	"stew@mail.com",
	"Fall2025",
	"13",
	"Prints numbers from 1 to 5 with space separation",
	"-5",
	"Infinite loop",
	"3",
	"int sum = a * b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 1; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints numbers from 0 to 4 with space separation",
	"public",
	"To define methods",
	"Constructors can have a return type",
	"public int calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	5,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	previous_education,
	previous_classes,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	19,
	NULL,
	"Emma",
	"Taylor",
	"2004-02-19",
	"2024-05-01",
	"emmat@mail.com",
	"Fall2024",
	"MIT",
	"CS50, CS100",
	"16",
	"Prints numbers from 1 to 5 with space separation",
	"Positive",
	"Prints even numbers from 0 to 8 with space seraration",
	"2",
	"int sum = a / b;",
	"1",
	"if (num / 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 1; i < 6; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints numbers from 0 to 8 with space separation",
	"void",
	"To initialize variables",
	"Constructors can be overloaded",
	"void calculateArea() { }",
	"Prints numbers from 0 to 8 with space separation",
	6,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	question_16,
	question_17,
	question_18,
	question_19,
	question_20,
	question_21,
	question_22,
	question_23,
	question_24,
	question_25,
	question_26,
	question_27,
	question_28,
	question_29,
	question_30,
	question_31,
	question_32,
	question_33,
	question_34,
	question_35,
	score,
	recommendation)
VALUES (
	20,
	87879586,
	"Harper",
	"Lee",
	"1999-06-16",
	"2023-04-01",
	"leeh@mail.com",
	"Spring2024",
	"11",
	"Prints numbers from 1 to 5 with space separation",
	"Negative",
	"Prints even numbers from 0 to 8 with space seraration",
	"1",
	"int sum = a + b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 1; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints even numbers from 0 to 8 with space separation",
	"public",
	"To perform arithmetic operations",
	"Constructors can be overloaded",
	"public int calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	"int[] numbers;",
	"arr[2];",
	"Calculates the sum of the numbers in the array",
	"String[] names = new String();",
	"It stores the number of elements in the array",
	"Inheritance allows a class to inherit properties and behaviors from another class",
	"Encapsulation allows a class to inherit properties and behaviors from another class",
	"Polymorphism allows a class to have multiple parent classes",
	"Method overriding allows a subclass to provide a specific implementation of a method that is already",
	"extends",
	"JavaFX",
	"A program that executes only once and terminates",
	"JButton",
	"To handle mouse events such as clicks",
	"Event handling in Java GUI programming is not supported",
	"To perform arithmetic operations",
	"FileReader",
	"To represent a file or directory path",
	"FileReader fileReader = new FileReader(&quotdata.txt&quot);",
	"To delete a file",
	21,
	111
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	previous_education,
	previous_classes,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	21,
	NULL,
	"Sam",
	"Ross",
	"2002-12-31",
	"2024-04-04",
	"sr@mail.com",
	"Fall2024",
	"WSU",
	"CS110",
	"16",
	"Prints numbers from 0 to 5 with space separation",
	"-5",
	"Prints numbers from 0 to 8 with space separation",
	"3",
	"int sum = a * b;",
	"0",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 0; i < 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Infinite loop",
	"public",
	"To create objects",
	"Constructors can be declared static",
	"public int calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	3,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	previous_education,
	previous_classes,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	22,
	NULL,
	"Isaac",
	"Martinez",
	"2004-02-10",
	"2023-11-12",
	"marty@mail.com",
	"Winter2025",
	"Seattle U",
	"CS100, CS111",
	"13",
	" Prints numbers from 0 to 5 with space separation",
	"Negative",
	"Prints even numbers from 0 to 8 with space seraration",
	"1",
	"int sum = a + b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 0; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints even numbers from 0 to 8 with space separation",
	"public",
	"To perform arithmetic operations",
	"Constructors can have a return type",
	"public int calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	10,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	23,
	15784754,
	"Caleb",
	"Morgan",
	"2003-02-03",
	"2023-01-04",
	"cm@mail.com",
	"Fall2024",
	"11",
	"Prints numbers from 1 to 5 with space separation",
	"Negative",
	"Prints numbers from 0 to 8 with space separation",
	"2",
	"int sum = a + b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 1; i < 6; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Infinite loop",
	"public",
	"To perform arithmetic operations",
	"Constructors can be overloaded",
	"void calculateArea() { }",
	"Defines a class named Rectangle with length and width attributes and a method to calculate the area",
	8,
	110
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	previous_education,
	previous_classes,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	question_16,
	question_17,
	question_18,
	question_19,
	question_20,
	question_21,
	question_22,
	question_23,
	question_24,
	question_25,
	question_26,
	question_27,
	question_28,
	question_29,
	question_30,
	question_31,
	question_32,
	question_33,
	question_34,
	question_35,
	score,
	recommendation)
VALUES (
	24,
	NULL,
	"Hank",
	"Tank",
	"2002-01-29",
	"2022-11-23",
	"ht@mail.com",
	"Fall2023",
	"PLU",
	"CS100",
	"11",
	"Prints numbers from 0 to 4 with space separation",
	"Negative",
	"Prints even numbers from 0 to 8 with space seraration",
	"1",
	"int sum = a + b;",
	"1",
	"if (num % 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 1; i <= 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Prints even numbers from 0 to 8 with space separation",
	"class",
	"To perform arithmetic operations",
	"Constructors can be inherited",
	"int calculateArea() { }",
	"Initializes length and width variables",
	"int[] numbers;",
	"arr[2];",
	"Finds the average of the numbers in the array",
	"String[] names = new String();",
	"It stores the index of the last element in the array",
	"Inheritance allows a class to override all methods of the superclass",
	"Encapsulation allows data to be hidden and accessed only through the methods of a class",
	"Polymorphism allows a method to have multiple implementations based on the object it is called with",
	"Method overriding allows a subclass to have multiple parent classes",
	"virtual",
	"AWT",
	"A program that executes only once and terminates",
	"JButton",
	"To define the appearance of the GUI components",
	"Event handling in Java GUI programming is not supported",
	"To read and write data to external files",
	"FileWriter",
	"To open a file for reading",
	"FileReader fileReader = new FileReader(&quotdata.txt&quot);",
	"To close a file",
	16,
	111
);

INSERT INTO students (
	student_id,
	sid,
	first_name,
	last_name,
	dob,
	date_quiz_taken,
	email,
	expected_term,
	question_1,
	question_2,
	question_3,
	question_4,
	question_5,
	question_6,
	question_7,
	question_8,
	question_9,
	question_10,
	question_11,
	question_12,
	question_13,
	question_14,
	question_15,
	score,
	recommendation)
VALUES (
	25,
	17888855,
	"Owen",
	"Evans",
	"2005-01-01",
	"2023-12-04",
	"ft@mail.com",
	"Spring2024",
	"16",
	"Infinite loop",
	"Negative",
	"Prints even numbers from 0 to 8 with space seraration",
	"1",
	"int sum = a - b;",
	"2",
	"if (num / 2 == 0) {<br>&emsp;System.out.println(&quot;Even&quot;);<br>} else {<br>&emsp;System.out.println(&quot;Odd&quot;);<br>}<br>",
	"for (int i = 0; i < 5; i++) {<br>&emsp;System.out.print(i + &quot; &quot;);<br>}<br>",
	"Infinite loop",
	"void",
	"To initialize variables",
	"Constructors can be inherited",
	"CalculateArea() { }",
	"Creates an object of the Rectangle class",
	3,
	110
);